### ISSUE TITLE
checklist before releasing a draft

### ISSUE THREAD

**Issue by bhpayne** [bhpayne/bureaucracy-guidebook#15]
- [ ] check for poor wording using `./report_common_errors.sh`
- [ ] did I include eveything that I meant to? See `./compare_includes_to_files.sh`
- [ ] generate DOCX, PDF, HTML, EPUB versions using `./make all`
- [ ] review content using <https://www.grammarly.com/>
- in each of the PDFs,
   - [ ] verify the index in each artifact is sorted correctly. See <https://github.com/processempathy/bureaucracy-guidebook/issues/16> and <https://www.ams.org/arc/tex/howto/index/0index-notes.pdf>
   - [ ] look for headers that exceed the page width. See <https://tex.stackexchange.com/a/26236/235813> and <https://tex.stackexchange.com/a/6866/235813>; more details on <https://www.overleaf.com/learn/latex/Articles/How_does_LaTeX_typeset_headers_and_footers%3F#Exploring_the_book_class>
   - [ ] review start-of-chapter pages to see where page number is at bottom of page
   - [ ] look for margin comments that run off the page. "see page" and ">>"
   - [ ] footnote in section 6.8 on Robert's Rules of Order is long. 
   - [ ] chapter 3 has a footnote on the start-of-chapter page
- [ ] click on links in the PDF/HTML/EPUB to ensure links are working
- in the generated HTML
   - [ ] search for " ," (space followed by comma) and correct instances by removing the space.
   - [ ] search for "page " and remove instances
   - [ ] search the HTML source code for 
```
[a-z]</p>
<p>
```
to find unintended spaces in the PDF.
- [ ] tag the release in git
